name: Publish One Click Apps

on:
    # push:
    #     branches: [main]
    workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 20

            - uses: actions/configure-pages@v5
            - run: npm ci
            - run: npm run build
            - uses: actions/deploy-pages@v4
